version: "3.9"
services:
  redis:
    image: library/redis:6.2
    ports:
    - "6379:6379"
  mongo:
    image: mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
